nodes: 1
tasks_per_node: 1
tag: jepa-eval-eeg
eval_name: eeg_classification_frozen
resume_checkpoint: false
data:
  datasets:
    - "/path/to/tuh/labeled/"
  num_classes: 2
  num_segments: 1
  resolution: 224
  num_workers: 4
  supervised: true
optimization:
  num_epochs: 500
  batch_size: 2
  weight_decay: 0.001
  lr: 0.001
  start_lr: 0.001
  final_lr: 0.0
  warmup: 0.
  use_bfloat16: false
pretrain:
  model_name: vit_small
  checkpoint_key: target_encoder
  clip_duration: null
  frames_per_clip: 32
  frame_step: 3
  tubelet_size: 4
  uniform_power: true
  use_sdpa: true
  use_silu: false
  tight_silu: false
  patch_size: 16
  folder: "/path/to/output_jepa/v9.2"
  checkpoint: "jepa-best.pth.tar"  # name of pretrained model file inside folder
  write_tag: jepa
